from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from knowledge_index import update_index

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "knowledge" / "generated" / "CURRENT_STATE.md"


def files_under(relative: str, suffixes: tuple[str, ...]) -> list[Path]:
    base = ROOT / relative
    if not base.exists():
        return []
    return sorted(
        path
        for path in base.rglob("*")
        if path.is_file()
        and path.suffix.lower() in suffixes
        and not any(part in {"node_modules", "target", ".venv", "dist", "build"} for part in path.parts)
    )


def count_pattern(paths: list[Path], pattern: str) -> int:
    regex = re.compile(pattern, re.MULTILINE)
    total = 0
    for path in paths:
        try:
            total += len(regex.findall(path.read_text(encoding="utf-8", errors="ignore")))
        except OSError:
            continue
    return total


def media_versions() -> dict[str, str]:
    pom = ROOT / "services" / "media-service" / "pom.xml"
    if not pom.exists():
        return {}
    text = pom.read_text(encoding="utf-8", errors="ignore")
    values: dict[str, str] = {}
    for label, pattern in {
        "java": r"<java\.version>([^<]+)</java\.version>",
        "spring-boot": r"<version>([^<]+)</version>",
    }.items():
        match = re.search(pattern, text)
        if match:
            values[label] = match.group(1).strip()
    return values


def python_dependencies() -> dict[str, str]:
    requirements = ROOT / "services" / "agent-service" / "requirements.txt"
    if not requirements.exists():
        return {}
    wanted = {"fastapi", "pydantic", "uvicorn", "pytest"}
    values: dict[str, str] = {}
    for raw in requirements.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        match = re.match(r"([A-Za-z0-9_.-]+)==([^;\s]+)", line)
        if match and match.group(1).lower() in wanted:
            values[match.group(1).lower()] = match.group(2)
    return values


def web_dependencies() -> dict[str, str]:
    package = ROOT / "apps" / "web" / "package.json"
    if not package.exists():
        return {}
    data = json.loads(package.read_text(encoding="utf-8"))
    merged = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
    return {key: merged[key] for key in ("react", "typescript", "vite") if key in merged}


def contract_paths() -> list[str]:
    base = ROOT / "contracts"
    if not base.exists():
        return []
    return [path.relative_to(ROOT).as_posix() for path in sorted(base.rglob("*")) if path.is_file()]


def format_map(values: dict[str, str]) -> str:
    return ", ".join(f"{key} {value}" for key, value in values.items()) or "not detected"


def render() -> str:
    java_main = files_under("services/media-service/src/main", (".java",))
    java_test = files_under("services/media-service/src/test", (".java",))
    python_main = files_under("services/agent-service/app", (".py",))
    python_test = files_under("services/agent-service/tests", (".py",))
    web_source = files_under("apps/web/src", (".ts", ".tsx", ".css"))
    contracts = contract_paths()
    local_acceptance = (ROOT / "scripts" / "local_acceptance.py").exists()
    java_test_methods = count_pattern(java_test, r"@Test\b")
    python_test_functions = count_pattern(python_test, r"^\s*(?:async\s+)?def\s+test_")
    media_routes = count_pattern(java_main, r"@(Get|Post|Put|Patch|Delete|Request)Mapping\b")
    agent_routes = count_pattern(python_main, r"@(?:app|router)\.(?:get|post|put|patch|delete)\b")

    lines = [
        "# Generated Current State",
        "",
        "> Generated by `python scripts/update_knowledge.py`. Do not edit by hand.",
        "",
        "## Workspace inventory",
        "",
        f"- Media Service: {len(java_main)} production Java files; {len(java_test)} test files; {java_test_methods} `@Test` methods.",
        f"- Agent Service: {len(python_main)} application Python files; {len(python_test)} test files; {python_test_functions} pytest test functions.",
        f"- React Web: {len(web_source)} TypeScript/TSX/CSS source files.",
        f"- Machine-readable contracts: {len(contracts)} files.",
        f"- Local localhost-only acceptance runner: {'present' if local_acceptance else 'missing'}.",
        "",
        "## Detected primary dependencies",
        "",
        f"- Media Service: {format_map(media_versions())}",
        f"- Agent Service: {format_map(python_dependencies())}",
        f"- React Web: {format_map(web_dependencies())}",
        "",
        "## HTTP surface approximation",
        "",
        f"- Media mapping annotations: {media_routes}",
        f"- Agent route decorators: {agent_routes}",
        "",
        "## Versioned contracts",
        "",
    ]
    lines.extend(f"- `{path}`" for path in contracts)
    if not contracts:
        lines.append("- None yet.")
    lines.extend(
        [
            "",
            "## Source-of-truth note",
            "",
            "Counts and versions above are structural observations, not release claims. Read the human-maintained knowledge pages for product semantics, boundaries and verified quality evidence.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Update or check generated project knowledge.")
    parser.add_argument("--check", action="store_true", help="Fail when generated knowledge is stale.")
    args = parser.parse_args()
    expected = render()

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        semantic_passed, semantic_stats = update_index(ROOT, check=True)
        if actual != expected:
            print(f"Knowledge drift detected: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            print("Run: python scripts/update_knowledge.py", file=sys.stderr)
            return 1
        if not semantic_passed:
            print("Semantic knowledge drift detected: knowledge/generated/SEMANTIC_INDEX.json", file=sys.stderr)
            print("Run: python scripts/update_knowledge.py", file=sys.stderr)
            return 1
        print(
            f"Semantic index check passed: {semantic_stats['sources']} sources, "
            f"{semantic_stats['chunks']} chunks."
        )
        print("Knowledge check passed.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Updated {OUTPUT.relative_to(ROOT)}")
    _, semantic_stats = update_index(ROOT)
    print(
        "Updated knowledge\\generated\\SEMANTIC_INDEX.json "
        f"({semantic_stats['sources']} sources, {semantic_stats['chunks']} chunks, "
        f"reused {semantic_stats['reused']}, computed {semantic_stats['computed']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
